import { createRouteHandlerClient } from '@supabase/auth-helpers-nextjs';
import { cookies } from 'next/headers';
import { NextRequest, NextResponse } from 'next/server';
import { Database } from '@/types/database';

// Teacher roles that should receive referral codes
const TEACHER_ROLES = ['resource', 'speech', 'ot', 'counseling', 'specialist'] as const;

export async function POST(request: NextRequest) {
  try {
    const { email, password, metadata } = await request.json();

    // Validate required fields
    if (!email || !password || !metadata) {
      return NextResponse.json(
        { error: 'Email, password, and metadata are required' },
        { status: 400 }
      );
    }

    // Validate email domain
    const emailDomain = email.split('@')[1];
    if (!emailDomain || 
        (!emailDomain.endsWith('.edu') && 
         !emailDomain.endsWith('.org') && 
         !emailDomain.includes('.k12.') && 
         !emailDomain.endsWith('.gov'))) {
      return NextResponse.json(
        { error: 'Email must be from an educational institution (.edu, .org, .k12., or .gov)' },
        { status: 400 }
      );
    }

    // Validate school site name
    if (metadata.school_site.length < 5 || !/\s/.test(metadata.school_site)) {
      return NextResponse.json(
        { error: 'Please enter your full school site name (no abbreviations - and spell correctly!)' },
        { status: 400 }
      );
    }

    const cookieStore = cookies();
    const supabase = createRouteHandlerClient<Database>({ cookies: () => cookieStore });

    // Sign up the user
    const { data: signUpData, error: signUpError } = await supabase.auth.signUp({
      email,
      password,
      options: {
        data: {
          full_name: metadata.full_name,
          state: metadata.state,
          school_district: metadata.school_district,
          school_site: metadata.school_site,
          role: metadata.role,
          works_at_multiple_schools: metadata.works_at_multiple_schools || false,
          additional_schools: metadata.additional_schools || []
        },
      },
    });

    if (signUpError) {
      return NextResponse.json({ error: signUpError.message }, { status: 400 });
    }

    if (!signUpData.user) {
      return NextResponse.json({ error: 'Failed to create user' }, { status: 500 });
    }

    // Create profile record
    const { error: profileError } = await supabase
      .from('profiles')
      .insert({
        id: signUpData.user.id,
        email: signUpData.user.email!,
        full_name: metadata.full_name,
        role: metadata.role,
        school_district: metadata.school_district,
        school_site: metadata.school_site,
        works_at_multiple_schools: metadata.works_at_multiple_schools || false,
        district_domain: emailDomain,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      });

    if (profileError) {
      // If profile creation fails, we should clean up the auth user
      // But for now, we'll just log the error
      console.error('Failed to create profile:', profileError);
      return NextResponse.json(
        { error: 'Failed to create user profile' },
        { status: 500 }
      );
    }

    // For teacher roles, ensure referral code is generated
    if (TEACHER_ROLES.includes(metadata.role)) {
      // Check if referral code was automatically generated by the trigger
      const { data: referralCode, error: checkError } = await supabase
        .from('referral_codes')
        .select('code')
        .eq('user_id', signUpData.user.id)
        .single();

      // If no referral code exists (trigger might have failed), generate one manually
      if (checkError || !referralCode) {
        const generateReferralCode = () => {
          const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
          let code = '';
          for (let i = 0; i < 6; i++) {
            code += chars[Math.floor(Math.random() * chars.length)];
          }
          return code;
        };

        // Try to generate a unique code
        let attempts = 0;
        let codeGenerated = false;
        
        while (!codeGenerated && attempts < 100) {
          attempts++;
          const newCode = generateReferralCode();
          
          // Check if code already exists
          const { data: existingCode } = await supabase
            .from('referral_codes')
            .select('code')
            .eq('code', newCode)
            .single();

          if (!existingCode) {
            // Insert the new code
            const { error: insertError } = await supabase
              .from('referral_codes')
              .insert({
                user_id: signUpData.user.id,
                code: newCode,
                uses_count: 0,
                created_at: new Date().toISOString(),
              });

            if (!insertError) {
              codeGenerated = true;
            }
          }
        }

        if (!codeGenerated) {
          console.error('Failed to generate referral code after 100 attempts');
        }
      }
    }

    return NextResponse.json({
      user: signUpData.user,
      session: signUpData.session,
    });
  } catch (error) {
    console.error('Signup error:', error);
    return NextResponse.json(
      { error: 'An unexpected error occurred' },
      { status: 500 }
    );
  }
}